export class TemasVentas{
    constructor(
        public id: number,
        public descripcion: string,
        public color: string,
        public imagen: string,
        public orden: number,
        public notificacion: number,
        public ocultar: number,
        public campo_notransaccion : number,
        public campo_fecha_registro : number,
        public campo_semana : number,
        public campo_vendedor : number,
        public campo_proyecto : number,
        public campo_cliente: number,
        public campo_telefono : number,
        public campo_email : number,
        public campo_noine : number,
        public campo_noimss : number,
        public campo_noinfonavit : number,
        public campo_nofoviste : number,
        public campo_tipo_propiedad : number,
        public campo_tipo_operacion : number,
        public campo_tipo_credito : number,
        public campo_forma_pago : number,
        public campo_institucion_credito : number,
        public campo_notario : number,
        public campo_propiedad : number,
        public campo_modelo_propiedad : number,
        public campo_especificacion_propiedad : number,
        public campo_precio: number,
        public campo_avance_construccion: number,
        public campo_monto_anticipo : number,
        public campo_monto_cobrado : number,
        public campo_fecha_entrega : number,
        public campo_meses_garantia : number,
        public campo_costo_mtto : number,
        public campo_estatus : number,
        public campo_meses_contrato: number,
        public campo_dias_pago: number,
        public campo_no_pago: number,
        public campo_nota : number,
        public campo_aut_por : number,
        public campo_estatus_ventas: number,
        public campo_ubicacion_propiedad: number
    ){}
}